In [1]:
from google.cloud import bigquery  # Conector oficial do banco de dados analítico (BigQuery) da Google.
from google.oauth2 import service_account  # Mecanismo de autenticação por chave/arquivo JSON de conta de serviço.
import pandas as pd  # A principal biblioteca de Data Science para tabelas (DataFrames) e manipulação matricial.
pd.set_option("display.max_columns", None)  # Não limita o número máximo de colunas exibidas na tela.
pd.set_option("display.max_rows", 10)  # Limita a exibição visual a no máximo 10 linhas para não travar a IDE.

In [2]:
# ==============================================================================
#  CONFIGURAÇÃO DE FONTES DE DADOS E INFRAESTRUTURA DE NUVEM
# ==============================================================================

# --- FONTE 1: REPOSITÓRIO REMOTO (GITHUB) ---
# URL base onde estão armazenados arquivos CSV públicos contendo dados históricos de filmes.
url_github_movies_dataset = "https://media.githubusercontent.com/media/lucas-aulas/dataset-movies/refs/heads/main"
# --- FONTE 2: AMBIENTE DE LEITURA (PROJETO COMPARTILHADO DO PROFESSOR) ---
# ID do projeto na Google Cloud de onde leremos uma tabela institucional de bilheterias.
fonte_gcp_project_id = "meu-projeto-eng-dados"

# --- DESTINO: AMBIENTE DE ESCRITA (PROJETO PRIVADO DO ALUNO) ---
# Caminho local do arquivo JSON que contém as credenciais de segurança (chave privada).
# ATENÇÃO: Nunca envie esta chave para o GitHub público! Ela equivale à senha do seu banco de dados.
meu_service_account_file = "C:\\Users\\1582367\\Documents\\Seminarios4\\secrets\\serviceaccount.json"
meu_gcp_project_id = "meu-projeto-eng-dados-512812"  # ID do seu projeto pessoal criado no GCP.

# Inicialização da autenticação e do cliente BigQuery
# Transforma o arquivo JSON em um objeto de credenciais aceito pelo Google.
gcp_credentials = service_account.Credentials.from_service_account_file(meu_service_account_file)

# O objeto 'client' funciona como a nossa ponte ativa de conexão/comunicação com a nuvem do Google.
bigquery_client = bigquery.Client(credentials=gcp_credentials)

In [3]:
df_imdb_filmes = pd.read_csv(f"{url_github_movies_dataset}/imdb_filmes.csv")

In [4]:
df_imdb_filmes

,Unnamed: 0,ID,TITLE,LINK,YEAR,DURATION,RATING_MPA,RATING_IMDB,VOTE,BUDGET,GROSS_WORLD_WIDE,GROSS_US_CANADA,GROSS_OPENING_WEEKEND,DIRECTOR,WRITER,STAR,GENRE,COUNTRY_ORIGIN,FILMING_LOCATION,PRODUCTION_COMPANY,LANGUAGE,WIN,NOMINATION,OSCAR
0,0,tt0073470,Strip Nude for Your Killer,https://www.imdb.com/title/tt0073470,1975,1h 38m,Not Rated,5.6,33000.0,NaN,NaN,NaN,NaN,Andrea Bianchi,"Andrea Bianchi, Massimo Felisatti","Edwige Fenech, Nino Castelnuovo, Femi Benussi","Erotic Thriller, Giallo, Slasher Horror, Horro...",Italy,"Milan, Lombardia, Italy",FRAL Cinematografica,Italian,0,0,0
1,1,tt0072764,Carry on Behind,https://www.imdb.com/title/tt0072764,1975,1h 30m,Not Rated,5.6,31000.0,NaN,NaN,NaN,NaN,Gerald Thomas,Dave Freeman,"Elke Sommer, Kenneth Williams, Bernard Bresslaw","Parody, Slapstick, Comedy",United Kingdom,"Bad Godesberg Way, Maidenhead, Berkshire, Engl...","The Rank Organisation, Peter Rogers Productions",English,0,0,0
2,2,tt0131526,"So Young, So Lovely, So Vicious...",https://www.imdb.com/title/tt0131526,1975,1h 30m,NaN,4.9,487.0,NaN,NaN,NaN,NaN,Silvio Amadio,"Silvio Amadio, Roberto Natale","Gloria Guida, Dagmar Lassander, Fred Robsahm","Drama, Mystery, Thriller",Italy,"Sardinia, Italy",Domiziana Internazionale Cinematografica,Italian,0,0,0
3,3,tt0073335,Mahogany,https://www.imdb.com/title/tt0073335,1975,1h 49m,PG,6.1,23000.0,NaN,NaN,5000000.0,NaN,"Berry Gordy, Tony Richardson, Jack Wormser","John Byrum, Toni Amber","Diana Ross, Billy Dee Williams, Anthony Perkins","Drama, Romance",United States,Marshall Field Co Department Store 111 N Sta...,"Motown Productions, Nikor Productions, Paramou...","English, Italian",0,0,1
4,4,tt0073006,Foreplay,https://www.imdb.com/title/tt0073006,1975,1h 15m,R,4.0,185.0,NaN,NaN,NaN,NaN,"John G Avildsen, Bruce Malmuth, Robert McCarty","Dan Greenburg, Jack Richardson, Bruce Jay Frie...","Irwin Corey, Pat Paulsen, Deborah Loomis","Parody, Satire, Sketch Comedy, Comedy",United States,NaN,SynFrank Enterprises,English,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33595,33595,tt0095428,Kansas,https://www.imdb.com/title/tt0095428,1988,1h 50m,R,5.5,14000.0,NaN,2432536.0,2432536.0,1274742.0,David Stevens,Spencer Eastman,"Matt Dillon, Andrew McCarthy, Leslie Hope","Crime, Drama, Romance, Thriller",United States,"Lawrence, Kansas, USA",Trans World Entertainment TWE,English,0,0,0
33596,33596,tt0094980,The Decline of Western Civilization Part II: T...,https://www.imdb.com/title/tt0094980,1988,1h 33m,R,7.2,45000.0,500000.0,373743.0,373743.0,45008.0,Penelope Spheeris,NaN,"Joe Perry, Steven Tyler, Gene Simmons","Documentary, Music",United States,"Los Angeles, California, USA",IRS World Media,English,0,0,0
33597,33597,tt0093170,Man Behind the Sun,https://www.imdb.com/title/tt0093170,1988,1h 45m,Not Rated,6.1,76000.0,NaN,NaN,NaN,NaN,TunFei Mou,"Mei Liu, Wen Yuan Mou, Dun Jing Teng","Gang Wang, Dai Yao Wu, Runshen Wang","Drama, History, Horror, War",Hong Kong,NaN,SilMetropole Organisation,Mandarin,0,0,0
33598,33598,tt0170783,Yesterday,https://www.imdb.com/title/tt0170783,1988,1h 24m,NaN,8.9,36000.0,NaN,NaN,NaN,NaN,Ivan Andonov,"Ivan Andonov, Vlado Daverov","Hristo Shopov, Georgi Staykov, Sofiya Kuzeva",Drama,Bulgaria,"Plovdiv, Bulgaria",NaN,"Bulgarian, English",0,0,0
33599,33599,tt0096516,Straight for the Heart,https://www.imdb.com/title/tt0096516,1988,1h 32m,NaN,6.8,262.0,NaN,NaN,NaN,NaN,La Pool,"Marcel Beaulieu, Michel Langlois, Yves Navarre","Matthias Habich, JohanneMarie Tremblay, Michel...","Drama, Romance, War","Canada, Switzerland","Montral, Qubec, Canada","Les films telescene inc, Xanadu Film AG",French,0,0,0

In [5]:
# Execução de uma consulta SQL estruturada diretamente dentro do Data Warehouse (BigQuery) da nuvem.
# O método '.to_dataframe()' faz o download do resultado da query SQL e o converte em uma tabela Pandas local.
# 'create_bqstorage_client=False' evita criar uma conexão otimizada adicional, mantendo a chamada simples.
df_boxoffice_dc_marvel = bigquery_client.query(
    f"SELECT * FROM {fonte_gcp_project_id}.raw.boxoffice_dc_marvel"
).to_dataframe(create_bqstorage_client=False)

In [6]:
df_boxoffice_dc_marvel

,int64_field_0,FILM,US_RELEASE_DATE,BOX_OFFICE_GROSS_DOMESTIC_US_AND_CANADA,BOX_OFFICE_GROSS_OTHER_TERRITORIES,BOX_OFFICE_GROSS_WORLDWIDE,BUDGET,MCU,PHASE,DISTRIBUTOR,MPAA_RATING,LENGTH,MINUTES,FRANCHISE,CHARACTER_FAMILY,DOMESTIC,GROSS_TO_BUDGET,ROTTEN_TOMATOES_CRITIC_SCORE,MALE_FEMALE_LED,YEAR,INFLATION_ADJUSTED_WORLDWIDE_GROSS,INFLATION_ADJUSTED_BUDGET,25X_PROD,BREAK_EVEN
0,113,NaN,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,NaN
1,89,The New Mutants,2020-08-28,23852659,25316935,49169594,67000000,False,NaN,20th Century Studios,PG-13,01:34:00,94.0,Marvel,X-Men,0.49,0.73,36.0,Co-starring,2020.0,49169594,67000000,167500000,Flop
2,98,Morbius,2022-04-01,73865530,93595431,167460961,75000000,False,NaN,Columbia Pictures,PG-13,01:44:00,104.0,Marvel,Spider-Man Allies and Villains,0.44,2.23,15.0,Male,2022.0,167460961,75000000,187500000,Flop
3,112,Madame Web,2024-02-14,42619699,54000000,96619699,80000000,False,NaN,Columbia Pictures,PG-13,01:56:00,116.0,Marvel,Spider-Man Allies and Villains,0.44,1.21,13.0,Female,2024.0,96619699,80000000,200000000,Flop
4,21,The Punisher,2004-04-16,33810189,20889916,54700105,33000000,False,NaN,Lions Gate Films,R,02:04:00,124.0,Marvel,Punisher,0.62,1.66,29.0,Male,2004.0,54700105,33000000,82500000,Flop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,78,Teen Titans Go! To the Movies,2018-07-27,29790236,22600000,52390236,10000000,False,NaN,Warner Bros.,PG,01:24:00,84.0,DC,Teen Titans,0.57,5.24,91.0,Co-starring,2018.0,63572054,12134333,25000000,Success
110,81,Aquaman,2018-12-21,335061807,816900000,1151961807,160000000,False,NaN,Warner Bros.,PG-13,02:23:00,143.0,DC,Aquaman,0.29,7.20,66.0,Male,2018.0,1397828760,194149320,400000000,Success
111,83,Shazam!,2019-04-05,140480049,227318962,367799011,100000000,False,NaN,Warner Bros.,PG-13,02:12:00,132.0,DC,Shazam,0.38,3.68,90.0,Male,2019.0,438356630,119183744,250000000,Success
112,87,Joker,2019-10-04,335477657,743480625,1078958282,55000000,False,NaN,Warner Bros.,R,02:02:00,122.0,DC,Batman,0.31,19.62,69.0,Male,2019.0,1285942872,65551059,137500000,Success
113,97,The Batman,2022-03-04,369345583,402900000,772245583,200000000,False,NaN,Warner Bros.,PG-13,02:56:00,176.0,DC,Batman,0.48,3.86,85.0,Male,2022.0,804033595,208232617,500000000,Success

In [9]:
import pandas_gbq

pandas_gbq.to_gbq(
    df_imdb_filmes,
    destination_table="bronze.imdb_filmes",
    project_id=meu_gcp_project_id,
    if_exists="replace",
    credentials=gcp_credentials,
)

pandas_gbq.to_gbq(
    df_boxoffice_dc_marvel,
    project_id=meu_gcp_project_id,
    destination_table="bronze.boxoffice_dc_marvel",
    if_exists="replace",
    credentials=gcp_credentials,
)