In [1]:
from google.cloud import bigquery
from google.oauth2 import service_account
import pandas as pd
import pandas_gbq

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

In [2]:
gcp_service_acc_file_aluno = "../secrets/serviceaccount.json"
gcp_id_do_projeto = "meu-projeto-eng-dados-512812"
my_gcp_cred = service_account.Credentials.from_service_account_file(gcp_service_acc_file_aluno)
my_gcp_client = bigquery.Client(credentials=my_gcp_cred)

In [3]:
df_silver = my_gcp_client.query(
    f"SELECT * FROM silver.complete_dc_marvel",
).to_dataframe(create_bqstorage_client=False)

In [ ]:
dim_film = (
    df_silver[["FILM", "GENRE", "RATING_MPA", "LANGUAGE", "BREAK_EVEN", "MCU", "MALE_FEMALE_LED", "PHASE"]]
    .drop_duplicates()
    .sort_values(by="FILM")#ORDENACAO POR FILME A-Z
    .reset_index(drop=True)#RESETA O INDEX ORIGINAL DO DF PARA 0,1,2,3,4,5,6,7,8,9
)

dim_film["ID_FILM"] = dim_film.index + 1

dim_film.head(5)

,FILM,GENRE,RATING_MPA,LANGUAGE,BREAK_EVEN,MCU,MALE_FEMALE_LED,PHASE,ID_FILM
0,Ant-Man,Superhero,PG-13,English,Success,True,Male,2.0,1
1,Ant-Man and the Wasp,Superhero,PG-13,English,Success,True,Co-starring,3.0,2
2,Ant-Man and the Wasp: Quantumania,Superhero,PG-13,English,Flop,True,Co-starring,5.0,3
3,Aquaman,Globetrotting Adventure,PG-13,English,Success,False,Male,NaN,4
4,Aquaman and the Lost Kingdom,Action Epic,PG-13,English,Flop,False,Male,NaN,5

In [11]:
dim_staff = (
    df_silver[["DIRECTOR", "WRITER", "STAR"]]
    .drop_duplicates()
    .sort_values(by=["DIRECTOR", "WRITER"])
    .reset_index(drop=True)
)

dim_staff["ID_STAFF"] = dim_staff.index + 1

dim_staff.head(3)

,DIRECTOR,WRITER,STAR,ID_STAFF
0,Alan Taylor,Christopher L Yost,"Chris Hemsworth, Natalie Portman, Tom Hiddleston",1
1,Andy Muschietti,Christina Hodson,"Ezra Miller, Michael Keaton, Sasha Calle",2
2,Andy Serkis,Kelly Marcel,"Tom Hardy, Woody Harrelson, Michelle Williams",3

In [15]:
dim_franchise = (
    df_silver[["FRANCHISE" , "CHARACTER_FAMILY"]]
    .drop_duplicates() 
    .sort_values(by=["FRANCHISE" , "CHARACTER_FAMILY"])
    .reset_index(drop=True)
)

dim_franchise["ID_FRANC"] = dim_franchise.index + 1 

dim_franchise.head(4)

  FRANCHISE CHARACTER_FAMILY  ID_FRANC
0        DC          Aquaman         1
1        DC           Batman         2
2        DC    Birds of Prey         3
3        DC      Blue Beetle         4

In [17]:
dim_production = (
    df_silver[["PRODUCTION_COMPANY", "DISTRIBUTOR", "COUNTRY_ORIGIN", "FILMING_LOCATION"]]
    .drop_duplicates()
    .sort_values(by=["PRODUCTION_COMPANY", "DISTRIBUTOR", "COUNTRY_ORIGIN", "FILMING_LOCATION"])
    .reset_index(drop=True)
)

dim_production["ID_PRODUCTION"] = dim_production.index + 1

dim_production.head(3)

,PRODUCTION_COMPANY,DISTRIBUTOR,COUNTRY_ORIGIN,FILMING_LOCATION,ID_PRODUCTION
0,20th Century Studios,20th Century Studios,United States,"Medfield State Hospital 45 Hospital Road, Med...",1
1,Amen Ra Films,New Line Cinema,United States,"Vancouver, British Columbia, Canada",2
2,Animal Logic,Warner Bros.,United States,"Disney Studios, Moore Park, Sydney, New South ...",3

In [18]:
dim_date = df_silver[["US_RELEASE_DATE"]].dropna().drop_duplicates().sort_values(by="US_RELEASE_DATE").reset_index(drop=True)

dim_date["YEAR"] = dim_date["US_RELEASE_DATE"].dt.year
dim_date["MONTH"] = dim_date["US_RELEASE_DATE"].dt.month
dim_date["QUARTER"] = dim_date["US_RELEASE_DATE"].dt.quarter

dim_date["ID_DATE"] = dim_date["US_RELEASE_DATE"].dt.strftime("%Y%m%d").astype(int)

dim_date.head(2)

  US_RELEASE_DATE  YEAR  MONTH  QUARTER   ID_DATE
0      1978-12-15  1978     12        4  19781215
1      1981-06-19  1981      6        2  19810619

In [19]:
fact_movies = df_silver.copy()

In [20]:
fact_movies = fact_movies.merge(
    dim_film,
    on=["FILM", "GENRE", "RATING_MPA", "LANGUAGE", "BREAK_EVEN", "MCU", "MALE_FEMALE_LED", "PHASE"],
    how="left",
)

In [21]:
fact_movies = fact_movies.merge(
    dim_staff,
    on=["DIRECTOR", "WRITER", "STAR"],
    how="left",
)

In [22]:
fact_movies = fact_movies.merge(
    dim_staff,
    on=["DIRECTOR", "WRITER", "STAR"],
    how="left",
)

In [23]:
fact_movies = fact_movies.merge(
    dim_franchise,
    on=["FRANCHISE", "CHARACTER_FAMILY"],
    how="left",
)

In [24]:
fact_movies = fact_movies.merge(
    dim_production,
    on=["PRODUCTION_COMPANY", "DISTRIBUTOR", "COUNTRY_ORIGIN", "FILMING_LOCATION"],
    how="left",
)

In [25]:
fact_movies = fact_movies.merge(
    dim_date,
    on=["US_RELEASE_DATE"],
    how="left",
)

In [ ]:
fact_movies = fact_movies[
    [
        "ID_FILM", "ID_STAFF", "ID_FRANCHISE", "ID_PRODUCTION",
        "ID_DATE", "BUDGET_x", "INFLATION_ADJUSTED_BUDGET",
        "GROSS_WORLD_WIDE", "INFLATION_ADJUSTED_WORLDWIDE_GROSS",
        "GROSS_US_CANADA", "DOMESTIC", "BOX_OFFICE_GROSS_OTHER_TERRITORIES",
        "GROSS_OPENING_WEEKEND", "GROSS_TO_BUDGET",
        "RATING_IMDB", "ROTTEN_TOMATOES_CRITIC_SCORE",
        "VOTE", "OSCAR", "NOMINATION", "WIN", "MINUTES"
    ]
]

In [26]:
fact_movies.head(3)

,BOX_OFFICE_GROSS_OTHER_TERRITORIES,BREAK_EVEN,BUDGET_x,CHARACTER_FAMILY,COUNTRY_ORIGIN,DIRECTOR,DISTRIBUTOR,DOMESTIC,FILM,FILMING_LOCATION,FRANCHISE,GENRE,GROSS_OPENING_WEEKEND,GROSS_TO_BUDGET,GROSS_US_CANADA,GROSS_WORLD_WIDE,ID,INFLATION_ADJUSTED_BUDGET,INFLATION_ADJUSTED_WORLDWIDE_GROSS,LANGUAGE,LINK,MALE_FEMALE_LED,MCU,MINUTES,NOMINATION,OSCAR,PHASE,PRODUCTION_COMPANY,RATING_IMDB,RATING_MPA,ROTTEN_TOMATOES_CRITIC_SCORE,STAR,US_RELEASE_DATE,VOTE,WIN,WRITER,YEAR_x,int64_field_0,ID_FILM,ID_STAFF_x,ID_STAFF_y,ID_FRANC,ID_PRODUCTION,YEAR_y,MONTH,QUARTER,ID_DATE
0,121200000.0,Flop,84500000.0,Birds of Prey,NaN,NaN,Warner Bros.,0.41,Birds of Prey (and the Fantabulous Emancipatio...,NaN,DC,NaN,NaN,2.43,NaN,NaN,NaN,99482958.0,2.417881e+08,NaN,NaN,Female,False,109.0,0,0,NaN,NaN,NaN,NaN,78,NaN,2020-02-07,0,0,NaN,2020,88,16,104,104,3,107,2020,2,1,20200207
1,186597000.0,Flop,200000000.0,X-Men,NaN,NaN,Twentieth Century Fox,0.26,Dark Phoenix,NaN,Marvel,NaN,NaN,1.26,NaN,NaN,NaN,200000000.0,2.524430e+08,NaN,NaN,Female,False,113.0,0,0,NaN,NaN,NaN,NaN,22,NaN,2019-06-07,0,0,NaN,2019,85,33,104,104,38,106,2019,6,2,20190607
2,741395911.0,Success,160000000.0,Spider-Man,NaN,NaN,Sony Pictures Entertainment,0.35,Spider-Man: Far From Home,NaN,Marvel,NaN,NaN,7.07,NaN,NaN,NaN,160000000.0,1.131928e+09,NaN,NaN,Male,True,129.0,0,0,3.0,NaN,NaN,NaN,90,NaN,2019-07-02,0,0,NaN,2019,86,69,104,104,35,105,2019,7,3,20190702

In [27]:
minhas_tabelas = {
    "dim_date": dim_date,
    "dim_film": dim_film,
    "dim_franchise": dim_franchise,
    "dim_production": dim_production,
    "dim_staff": dim_staff,
    "fact_movies": fact_movies,
}

for key, value in minhas_tabelas.items():
    print(key)

    pandas_gbq.to_gbq(
        value,
        project_id=gcp_id_do_projeto,
        destination_table=f"gold.{key}",
        if_exists="replace",
        credentials=my_gcp_cred,
    )

dim_date
dim_film
dim_franchise
dim_production
dim_staff
fact_movies

In [28]:
minhas_tabelas

{'dim_date':     US_RELEASE_DATE  YEAR  MONTH  QUARTER   ID_DATE
 0        1978-12-15  1978     12        4  19781215
 1        1981-06-19  1981      6        2  19810619
 2        1983-06-17  1983      6        2  19830617
 3        1984-11-21  1984     11        4  19841121
 4        1986-08-01  1986      8        3  19860801
 ..              ...   ...    ...      ...       ...
 108      2023-06-16  2023      6        2  20230616
 109      2023-08-18  2023      8        3  20230818
 110      2023-11-10  2023     11        4  20231110
 111      2023-12-20  2023     12        4  20231220
 112      2024-02-14  2024      2        1  20240214

 [113 rows x 5 columns],
 'dim_film':                                   FILM                    GENRE RATING_MPA  \
 0                              Ant-Man                Superhero      PG-13
 1                 Ant-Man and the Wasp                Superhero      PG-13
 2    Ant-Man and the Wasp: Quantumania                Superhero      PG-13
 3                              Aquaman  Globetrotting Adventure      PG-13
 4         Aquaman and the Lost Kingdom              Action Epic      PG-13
 ..                                 ...                      ...        ...
 108                  X-Men: Apocalypse                Superhero      PG-13
 109         X-Men: Days of Future Past                Superhero      PG-13
 110                 X-Men: First Class                Superhero      PG-13
 111              X-Men: The Last Stand                Superhero      PG-13
 112                                 X2                      NaN        NaN

     LANGUAGE BREAK_EVEN    MCU MALE_FEMALE_LED  PHASE  ID_FILM
 0    English    Success   True            Male    2.0        1
 1    English    Success   True     Co-starring    3.0        2
 2    English       Flop   True     Co-starring    5.0        3
 3    English    Success  False            Male    NaN        4
 4    English       Flop  False            Male    NaN        5
 ..       ...        ...    ...             ...    ...      ...
 108  English    Success  False            Male    NaN      109
 109  English    Success  False            Male    NaN      110
 110  English       Flop  False            Male    NaN      111
 111  English       Flop  False            Male    NaN      112
 112      NaN    Success  False            Male    NaN      113

 [113 rows x 9 columns],
 'dim_franchise':    FRANCHISE                CHARACTER_FAMILY  ID_FRANC
 0         DC                         Aquaman         1
 1         DC                          Batman         2
 2         DC                   Birds of Prey         3
 3         DC                     Blue Beetle         4
 4         DC                     Constantine         5
 ..       ...                             ...       ...
 33    Marvel                       Shang-Chi        34
 34    Marvel                      Spider-Man        35
 35    Marvel  Spider-Man Allies and Villains        36
 36    Marvel                            Thor        37
 37    Marvel                           X-Men        38

 [38 rows x 3 columns],
 'dim_production':                  PRODUCTION_COMPANY                   DISTRIBUTOR  \
 0              20th Century Studios          20th Century Studios
 1                     Amen Ra Films               New Line Cinema
 2                      Animal Logic                  Warner Bros.
 3                  Artistry Limited             Tri-Star Pictures
 4               Atlas Entertainment                  Warner Bros.
 ..                              ...                           ...
 102  Warner Bros Pictures Animation                  Warner Bros.
 103                             NaN            Paramount Pictures
 104                             NaN  Sony Pictures Entertainment
 105                             NaN         Twentieth Century Fox
 106                             NaN                  Warner Bros.

      COUNTRY_ORIGIN                                   FILMING_LOCATION  \
 0     United States  Medfield State Hospital  45 Hospital Road, Med...
 1     United States                Vancouver, British Columbia, Canada
 2     United States  Disney Studios, Moore Park, Sydney, New South ...
 3    United Kingdom                             Chicago, Illinois, USA
 4     United States               Fuerteventura, Canary Islands, Spain
 ..              ...                                                ...
 102   United States              Washington, District of Columbia, USA
 103             NaN                                                NaN
 104             NaN                                                NaN
 105             NaN                                                NaN
 106             NaN                                                NaN

      ID_PRODUCTION
 0                1
 1                2
 2                3
 3                4
 4                5
 ..             ...
 102            103
 103            104
 104            105
 105            106
 106            107

 [107 rows x 5 columns],
 'dim_staff':               DIRECTOR                WRITER  \
 0          Alan Taylor    Christopher L Yost
 1      Andy Muschietti      Christina Hodson
 2          Andy Serkis          Kelly Marcel
 3              Ang Lee              Stan Lee
 4    Angel Manuel Soto  Gareth DunnetAlcocer
 ..                 ...                   ...
 99         Zack Snyder              Bob Kane
 100        Zack Snyder          Dave Gibbons
 101        Zack Snyder         David S Goyer
 102        Zack Snyder          Jerry Siegel
 103                NaN                   NaN

                                                  STAR  ID_STAFF
 0    Chris Hemsworth, Natalie Portman, Tom Hiddleston         1
 1            Ezra Miller, Michael Keaton, Sasha Calle         2
 2       Tom Hardy, Woody Harrelson, Michelle Williams         3
 3           Eric Bana, Jennifer Connelly, Sam Elliott         4
 4            Xolo Mariduea, Bruna Marquezine, Becky G         5
 ..                                                ...       ...
 99               Ben Affleck, Henry Cavill, Amy Adams       100
 100  Jackie Earle Haley, Patrick Wilson, Carla Gugino       101
 101          Henry Cavill, Amy Adams, Michael Shannon       102
 102               Ben Affleck, Gal Gadot, Jason Momoa       103
 103                                               NaN       104

 [104 rows x 4 columns],
 'fact_movies':      BOX_OFFICE_GROSS_OTHER_TERRITORIES BREAK_EVEN     BUDGET_x  \
 0                           121200000.0       Flop   84500000.0
 1                           186597000.0       Flop  200000000.0
 2                           741395911.0    Success  160000000.0
 3                            22600000.0    Success   10000000.0
 4                           495900000.0    Success  230000000.0
 ..                                  ...        ...          ...
 108                         152498032.0    Success  100000000.0
 109                         104010057.0    Success   80000000.0
 110                         160160000.0    Success   35000000.0
 111                            213000.0       Flop    5600000.0
 112                         113900000.0       Flop   90000000.0

     CHARACTER_FAMILY COUNTRY_ORIGIN                                  DIRECTOR  \
 0      Birds of Prey            NaN                                       NaN
 1              X-Men            NaN                                       NaN
 2         Spider-Man            NaN                                       NaN
 3        Teen Titans            NaN                                       NaN
 4         Spider-Man            NaN                                       NaN
 ..               ...            ...                                       ...
 108           Batman  United States                           Joel Schumacher
 109           Batman  United States                                Tim Burton
 110           Batman  United States                                Tim Burton
 111           Batman  United States  Kevin Altieri, Boyd Kirkland, Frank Paur
 112   Justice League  United States                 Jared Stern, Sam J Levine

                       DISTRIBUTOR  DOMESTIC  \
 0                    Warner Bros.      0.41
 1           Twentieth Century Fox      0.26
 2    Sony Pictures Entertainment       0.35
 3                    Warner Bros.      0.57
 4    Sony Pictures Entertainment       0.35
 ..                            ...       ...
 108                  Warner Bros.      0.55
 109                  Warner Bros.      0.61
 110                  Warner Bros.      0.61
 111                  Warner Bros.      0.96
 112                  Warner Bros.      0.45

                                                   FILM  \
 0    Birds of Prey (and the Fantabulous Emancipatio...
 1                                         Dark Phoenix
 2                            Spider-Man: Far From Home
 3                        Teen Titans Go! To the Movies
 4                               The Amazing Spider-Man
 ..                                                 ...
 108                                     Batman Forever
 109                                     Batman Returns
 110                                             Batman
 111                       Batman: Mask of the Phantasm
 112                            DC League of Super-Pets

                                       FILMING_LOCATION FRANCHISE  \
 0                                                  NaN        DC
 1                                                  NaN    Marvel
 2                                                  NaN    Marvel
 3                                                  NaN        DC
 4                                                  NaN    Marvel
 ..                                                 ...       ...
 108  Alcatraz Island, San Francisco Bay, California...        DC
 109  Stage 12, Universal Studios  100 Universal Cit...        DC
 110  Knebworth House, Knebworth, Hertfordshire, Eng...        DC
 111  Warner Brothers Burbank Studios  4000 Warner B...        DC
 112              Washington, District of Columbia, USA        DC

                    GENRE  GROSS_OPENING_WEEKEND  GROSS_TO_BUDGET  \
 0                    NaN                    NaN             2.43
 1                    NaN                    NaN             1.26
 2                    NaN                    NaN             7.07
 3                    NaN                    NaN             5.24
 4                    NaN                    NaN             3.30
 ..                   ...                    ...              ...
 108            Superhero             52784433.0             3.37
 109         Dark Fantasy             45687711.0             3.34
 110          Action Epic             40489746.0            11.76
 111  HandDrawn Animation              1189975.0             1.04
 112   Computer Animation             23003441.0             2.31

      GROSS_US_CANADA  GROSS_WORLD_WIDE         ID  INFLATION_ADJUSTED_BUDGET  \
 0                NaN               NaN        NaN                 99482958.0
 1                NaN               NaN        NaN                200000000.0
 2                NaN               NaN        NaN                160000000.0
 3                NaN               NaN        NaN                 12134333.0
 4                NaN               NaN  tt0948470                230000000.0
 ..               ...               ...        ...                        ...
 108      184069126.0       336567158.0  tt0112462                199935422.0
 109      162924631.0       266941512.0  tt0103776                173742884.0
 110      251409241.0       411569241.0  tt0096895                 86004479.0
 111        5635204.0         5863139.0  tt0106364                 11808504.0
 112       93657117.0       207557117.0  tt8912936                 93704678.0

      INFLATION_ADJUSTED_WORLDWIDE_GROSS LANGUAGE  \
 0                          2.417881e+08      NaN
 1                          2.524430e+08      NaN
 2                          1.131928e+09      NaN
 3                          6.357205e+07      NaN
 4                          7.579307e+08      NaN
 ..                                  ...      ...
 108                        6.729170e+08  English
 109                        5.797250e+08  English
 110                        1.011337e+09  English
 111                        1.233188e+07  English
 112                        2.161008e+08  English

                                      LINK MALE_FEMALE_LED    MCU  MINUTES  \
 0                                     NaN          Female  False    109.0
 1                                     NaN          Female  False    113.0
 2                                     NaN            Male   True    129.0
 3                                     NaN     Co-starring  False     84.0
 4    https://www.imdb.com/title/tt0948470            Male  False    136.0
 ..                                    ...             ...    ...      ...
 108  https://www.imdb.com/title/tt0112462            Male  False    121.0
 109  https://www.imdb.com/title/tt0103776            Male  False    126.0
 110  https://www.imdb.com/title/tt0096895            Male  False    126.0
 111  https://www.imdb.com/title/tt0106364            Male  False     76.0
 112  https://www.imdb.com/title/tt8912936            Male  False    106.0

      NOMINATION  OSCAR  PHASE              PRODUCTION_COMPANY  RATING_IMDB  \
 0             0      0    NaN                             NaN          NaN
 1             0      0    NaN                             NaN          NaN
 2             0      0    3.0                             NaN          NaN
 3             0      0    NaN                             NaN          NaN
 4             0      0    NaN                             NaN          6.9
 ..          ...    ...    ...                             ...          ...
 108          26      3    NaN                     Warner Bros          5.4
 109          29      2    NaN                     Warner Bros          7.1
 110          28      0    NaN                     Warner Bros          7.5
 111           0      0    NaN           Warner Bros Animation          7.8
 112           9      0    NaN  Warner Bros Pictures Animation          7.1

     RATING_MPA  ROTTEN_TOMATOES_CRITIC_SCORE  \
 0          NaN                            78
 1          NaN                            22
 2          NaN                            90
 3          NaN                            91
 4        PG-13                            71
 ..         ...                           ...
 108      PG-13                            40
 109      PG-13                            81
 110      PG-13                            76
 111         PG                            82
 112         PG                            72

                                                 STAR US_RELEASE_DATE    VOTE  \
 0                                                NaN      2020-02-07       0
 1                                                NaN      2019-06-07       0
 2                                                NaN      2019-07-02       0
 3                                                NaN      2018-07-27       0
 4                                                NaN      2012-07-03  722000
 ..                                               ...             ...     ...
 108          Val Kilmer, Tommy Lee Jones, Jim Carrey      1995-06-16  272000
 109  Michael Keaton, Danny DeVito, Michelle Pfeiffer      1992-06-19  336000
 110     Michael Keaton, Jack Nicholson, Kim Basinger      1989-06-23  415000
 111          Kevin Conroy, Dana Delany, Hart Bochner      1993-12-25   59000
 112        Dwayne Johnson, Kevin Hart, Kate McKinnon      2022-07-29   78000

      WIN        WRITER  YEAR_x  int64_field_0  ID_FILM  ID_STAFF_x  \
 0      0           NaN    2020             88       16         104
 1      0           NaN    2019             85       33         104
 2      0           NaN    2019             86       69         104
 3      0           NaN    2018             78       81         104
 4      0           NaN    2012             48       82         104
 ..   ...           ...     ...            ...      ...         ...
 108    0      Bob Kane    1995             11       12          47
 109    0      Bob Kane    1992              9       13          93
 110    0      Bob Kane    1989              7        9          94
 111    0  Alan Burnett    1993             10       15          59
 112    0   Jared Stern    2022            101       31          40

      ID_STAFF_y  ID_FRANC  ID_PRODUCTION  YEAR_y  MONTH  QUARTER   ID_DATE
 0           104         3            107    2020      2        1  20200207
 1           104        38            106    2019      6        2  20190607
 2           104        35            105    2019      7        3  20190702
 3           104        14            107    2018      7        3  20180727
 4           104        35            105    2012      7        3  20120703
 ..          ...       ...            ...     ...    ...      ...       ...
 108          47         2             79    1995      6        2  19950616
 109          93         2             97    1992      6        2  19920619
 110          94         2             87    1989      6        2  19890623
 111          59         2            102    1993     12        4  19931225
 112          40         9            103    2022      7        3  20220729

 [113 rows x 47 columns]}